# declare python version
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov
  - pip install coveralls
script:
  - py.test
  - py.test --cov
branches:
  only:
    - shopping_cart
after_success:
  - coveralls
